afterglowss/MeteorDodgeGamewithShooting

- MeteorDodgeGamewithShooting/bullet.h
- MeteorDodgeGamewithShooting/game.h
- MeteorDodgeGamewithShooting/meteor.h
- MeteorDodgeGamewithShooting/player.h
feat: 게임에 필요한 상수 정의 (#21)
Closes #21
- 게임에 필요한 상수 정의
- 모든 헤더 파일
(또는 해당 파일들)
---
> feat: 게임에 필요한 상수 정의 (#21)

- MeteorDodgeGamewithShooting/game.c
- MeteorDodgeGamewithShooting/game.h
Closes #22
- 점수 및 라이프 UI 출력하는 DrawUI 함수 작성
- `game.h`
- `game.c`
- 함수가.... 뭐가 없는 것 같지만 나중에 풍부해질 거에요^^
---
> feat: 점수 및 라이프 UI 출력 (#22)

- MeteorDodgeGamewithShooting/game.h
fix: screen size 변경 (#28)
Closes #28 
- 게임 화면 가로 1200, 세로 800으로 변경하였습니다.
- `game.h`
- 과제 조건에 호환성 목록도 있었으니 노트북 마다 화면 크기 차이도 고려해야 할 것 같습니다.
---
> fix: screen size 변경 (#28)

- MeteorDodgeGamewithShooting/player.c
- MeteorDodgeGamewithShooting/player.h
플레이어 이동 구현(#7)
Closes #7 
- 플레이어 이동 구현
- player.h / player.c
- src/player.c
- include/player.h
(또는 해당 파일들)
- 플레이어 이동 구현입니다. 
---
> feat: 플레이어 이동 구현 (#7)

- MeteorDodgeGamewithShooting/meteor.c
운석 이동 처리 구현(수정) #17
Closes #17 
- 운석이 화면 내부 랜덤한 방향으로 속도5로 이동함(meteor.c)
- MeteorDodgeGamewithShooting/meteor.c
https://github.com/user-attachments/assets/b7d73d3d-f618-4b88-aeb4-4a6d85867d90
- main.c를 아래의 코드로 변경하여 빌드해야 작동 확인 가능합니다.
int main(void)
{
InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "Hello Raylib!");
InitMeteors();
while (!WindowShouldClose())
{
UpdateMeteors();
BeginDrawing();
ClearBackground(BLACK);
DrawMeteors();
EndDrawing();
}
CloseWindow();
return 0;
}
---
> 운석 이동 처리 구현 #17

- MeteorDodgeGamewithShooting/bullet.c
- MeteorDodgeGamewithShooting/bullet.h
feat: 총알 생성 및 그리기 (#13)
Closes #13 
- 총알 생성 및 그리기
- bullet.c
- bullet.h
- 
- 참고해야 할 사항이나 설명이 필요한 부분이 있다면 여기에 작성해 주세요.
테스트 했던 메인함수
`int main(void)
{
InitWindow(800, 600, "Hello Raylib!");
while (!WindowShouldClose())
{
if (IsMouseButtonPressed(MOUSE_LEFT_BUTTON))
FireBullet();
BeginDrawing();
ClearBackground(RAYWHITE);
DrawBullets();
EndDrawing();
}
CloseWindow();
return 0;
}`
---
> feat: 총알 생성 및 그리기 (#13)

- MeteorDodgeGamewithShooting/bullet.c
총알 이동 및 화면 밖 제거(#14 )
Closes #14 
- 총알 위치 업데이트
- 쿨다운으로 연속적인 총알 생성 제한
- bullet.c
- 
https://github.com/user-attachments/assets/5b183ca8-5889-4180-be3c-96c76eb684ac
- 참고해야 할 사항이나 설명이 필요한 부분이 있다면 여기에 작성해 주세요.
```
int main(void)
{
InitWindow(800, 600, "Hello Raylib!");
while (!WindowShouldClose())
{
if (IsMouseButtonPressed(MOUSE_LEFT_BUTTON))
FireBullet();
UpdateBullets();
BeginDrawing();
ClearBackground(RAYWHITE);
DrawBullets();
EndDrawing();
}
CloseWindow();
return 0;
}
```
---
> feat: 총알 이동 및 화면 밖 제거(#14)

- MeteorDodgeGamewithShooting/player.c
- MeteorDodgeGamewithShooting/player.h
플레이어 가속력 구현 (#8)
Closes #8 
- 플레이어 이동 시 가속력 구현
- 방향키 좌, 우는 회전 / 위 키는 플레이어가 바라보는 방향으로 이동
- MeteorDodgeGamewithShooting/player.c
- MeteorDodgeGamewithShooting/player.h
https://github.com/user-attachments/assets/3d468519-12ee-4ba3-b345-a90414039116
- 사용 안하는 전처리 지시자 다음 작업할 때 삭제해 놓겠습니다.
---
> feat: 플레이어 가속력 구현 (#8)

- MeteorDodgeGamewithShooting/main-복사.c
게임 오버 및 재시작 기능 (#23)
Closes #23 
- 게임 오버 화면 출력
- 플레이어, 총알, 운석의 위치를 변경하는 update 함수 입력
- 임시로 A 버튼 누를 시 게임오버 상태가 되도록 구현
- 게임 오버 상태에서 Enter 입력 시 게임 재시작
- 게임 오버 상태에서 BackSpace 입력 시 시작 화면
- main-복사.c
https://github.com/user-attachments/assets/9ff1ed3c-7d45-4121-a12d-0d523e8150a8
- 현재 게임 재시작 시 총알이 그대로 남아있는 것은 총알 비활성화를 해도 bullet.c 내부적으로 사용중인 bullet이 존재하기 때문으로 예상됩니다. #41 이슈 수정 이후에 제대로 초기화 되는지 확인이 필요합니다.
- 현재는 player와 bullet의 속도가 굉장히 느립니다. 이와 관련해서 수정이 필요할 것이라 여겨집니다.
---
> feat: 게임 오버 및 재시작 기능 (#23)

- MeteorDodgeGamewithShooting/player.c
플레이어 회전 방향 삼각형 표시 (#9)
Closes #9 
- 플레이어가 바라보는 방향으로 삼각형 드로잉
- 플레이어 좌표 기준으로 HEAD, LEFT, RIGHT 계산
- MeteorDodgeGamewithShooting/player.c
https://github.com/user-attachments/assets/dda3c42c-7e16-462f-9590-c94768f42b07
- 플레이어 크기,색상,모양 문제있으면 수정하겠습니다.
---
int main(void)
{
Player player;
InitWindow(1400, 800, "Hello Raylib!"); // 1200 800
InitPlayer(&player);
while (!WindowShouldClose())
{
BeginDrawing();
ClearBackground(RAYWHITE);
//DrawText("raylib with Visual Studio!", 200, 200, 20, DARKGRAY);
UpdatePlayer(&player);
DrawPlayer(&player);
EndDrawing();
}
CloseWindow();
return 0;
}
> feat: 플레이어 회전 방향 삼각형 표시 (#9)

- MeteorDodgeGamewithShooting/bullet.c
- MeteorDodgeGamewithShooting/bullet.h
retector: 총알 포인터 배열로 변경 (#41)
Closes #41 
- 함수에 총알을 포인터 배열로 전달하도록 변경
- bullet.c
- bullet.h
- 코드만 수정하여 영상은 따로 첨부하지 않았습니다.
---
> retector: 총알 포인터 배열로 변경 (#41)

- MeteorDodgeGamewithShooting/player.c
- MeteorDodgeGamewithShooting/player.h
플레이어 무적 깜빡이기 처리 (#10)
Closes #10 
- 플레이어 무적 깜빡이기 구현
- player.h에서 Player구조체 head와 isCollision 추가
- playerCollision 함수 구현
- Meteor-Dodge-Game-with-Shooting/player.c
- Meteor-Dodge-Game-with-Shooting/player.h
https://github.com/user-attachments/assets/8bcefeea-e28a-462f-887f-015f3b441947
- playerCollision 함수 호출하면 깜빡이기 작동합니다.
- 충돌 후 player는 잠시 움직일 수 없습니다.
- 테스트용 main-복사
#include "bullet.h"
int main(void)
{
InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "Meteor Dodge Game With Shooting");
Player player;
InitPlayer(&player);
Meteor meteors[MAX_METEORS];
InitMeteors();
Bullet bullets[MAX_BULLETS] = { 0 };
bool gameStarted = false;
bool gameOver = false;
int selectedMenu = 0;
const char* menuItems[] = { …
> feat: 플레이어 무적 깜빡이기 처리 (#10)

- MeteorDodgeGamewithShooting/meteor.c
- MeteorDodgeGamewithShooting/meteor.h
운석과 총알 충돌 처리 구현 (#20)
Closes #20 
- 운석과 총알 충돌 시, 운석과 총알 사라짐.(meteor.h, meteor.c)
- 사라진 운석은 화면 밖에서 재생성됨.
- meteor.h, meteor.c 코드 변경
- MeteorDodgeGamewithShooting/meteor.c
- MeteorDodgeGamewithShooting/meteor.h
(또는 해당 파일들)
https://github.com/user-attachments/assets/daceccdf-0806-4778-b448-0e7000b22d07
- bullet.h에 "#pragma once"가 없어서 빌드 오류가 나길래 임의로 추가해 빌드했습니다. 추후에 bullet.h에 추가해주세요.
- 아래의 main-복사.c코드로 빌드해주세요.
#include "bullet.h"
int main(void)
{
InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "Meteor Dodge Game With Shooting");
Player player;
InitPlayer(&player);
Meteor meteors[MAX_METEORS];
InitMeteors(meteors);
Bullet bullets[MAX_BULLETS] = { 0 };
bool gameStarted = false;
bool gameOver = false;
int …
> 운석과 총알 충돌 처리 구현 (#20)

- MeteorDodgeGamewithShooting/game.c
- MeteorDodgeGamewithShooting/game.h
- MeteorDodgeGamewithShooting/main-복사.c
- MeteorDodgeGamewithShooting/meteor.c
충돌 파편 애니메이션 (#25)
Closes #25 
- 운석과 총알 충돌 시 운석으로부터 회색 파편 효과가 발생함
- 운석과 플레이어 충돌 시 운석으로부터 빨간색 파편 효과가 발생함
- 충돌 시 GenerateExplosion함수를 호출하기 위해 meteor.c 수정
- main-복사.c 현재까지 수정된 내용 포함하여 리팩토링
- main-복사.c에 `UpdateParticles();`, `DrawParticles();` 삽입
- `game.c`
- `game.h`
- `meteor.c`
- `main-복사.c`
https://github.com/user-attachments/assets/3b36895a-d81b-4786-ab3a-8b1155146dcb
- main-복사.c를 업데이트 하였습니다. 그대로 빌드해서 플레이하시면 충돌 파편 확인 가능합니다.
- merge 이후 develop에 수정 버전의 main-복사.c가 있습니다. develop에서 pull 해서 사용하시면 되겠습니다.
---
> feat: 충돌 파편 애니메이션 (#25)

- MeteorDodgeGamewithShooting/bullet.c
- MeteorDodgeGamewithShooting/bullet.h
feat: 총알 생성 및 발사 위치 조정(#48 )
Closes #48 
- 총알 생성 위치를 player의 head로 변경
- 총알 발사 방향을 발사 당시 player가 바라보고 있던 방향으로 변경
- bullet.c
- bullet.h
- 
https://github.com/user-attachments/assets/1feb4f10-9b51-45e7-a2eb-f3c8091652b6
- 테스트 위해 사용했던 main.c 함수입니다(bullet 관련 함수에 인자를 추가하기만 했습니다.)
```
#include "bullet.h"
int main(void)
{
InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "Meteor Dodge Game With Shooting");
Player player;
InitPlayer(&player);
Meteor meteors[MAX_METEORS];
InitMeteors();
Bullet bullets[MAX_BULLETS] = { 0 };
bool gameStarted = false;
bool gameOver = false;
int selectedMenu = 0;
const char* menuItems[] = { "Start", "Score", "Credits", "Exit" };
const int menuCount = 4;
int score = 0;
int highScore = …
```
> feat: 총알 생성 및 발사 위치 조정(#48)

- MeteorDodgeGamewithShooting/main-복사.c
- MeteorDodgeGamewithShooting/meteor.c
- MeteorDodgeGamewithShooting/meteor.h
점수 시스템 구현 (#62)
Closes #62 
- 게임 시작 시 score 0으로 초기화
- 운석과 총알 충돌 시 score += 100
- highScore보다 현재 score가 높으면 highScore 갱신
- `meteor.c`, `meteor.h`, `main-복사.c`
https://github.com/user-attachments/assets/7c8398ba-11cb-4fa8-b711-0969a8a472da
- meteor.c, meteor.h, main-복사.c가 모두 변경되었습니다.
- main-복사.c 에는 score와 관련된 부분이 바뀌어서 커밋되었으니 빌드에 포함시켜서 실행해보시면 됩니다.
- 특히 UpdateMeteors의 매개변수에 &score가 추가되었으므로 확인 부탁드립니다.
---
> feat: 점수 시스템 구현 (#62)

- MeteorDodgeGamewithShooting/player.c
플레이어 화면 밖으로 이동 제한 (#36)
Closes #36 
- 플레이어 화면 밖으로 이동 제한 구현
- 꼭지점을 각각을 계산해서 자연스럽게 화면 밖으로 나가지 못하도록 함 🚀 Pull Request 제목
플레이어 화면 밖으로 이동 제한 (#36)
Closes #36 
- 플레이어 화면 밖으로 이동 제한 구현
- 꼭지점을 각각을 계산해서 자연스럽게 화면 밖으로 나가지 못하도록 함 
- player.c
https://github.com/user-attachments/assets/b0110dff-e768-467c-99d4-1f65e68a6da1
- 잔상효과에 대한 화면 제한은 따로 구현하지 않았습니다
---
> feat: 플레이어 화면 밖으로 이동 제한 (#36)

- MeteorDodgeGamewithShooting/item.h
아이템 파일 생성 및 시작 정의 (#70)
Closes #70 
- 아이템에 필요한 enum 정의 ItemType
- 구조체 정의 Item
- 함수 정의 InitItem UpdateItem DrawItem
- `item.c`
- `item.h`
---
> feat: 아이템 파일 생성 및 시작 정의 (#70)

- MeteorDodgeGamewithShooting/MeteorDodgeGamewithShooting.vcxproj
- MeteorDodgeGamewithShooting/MeteorDodgeGamewithShooting.vcxproj.filters
- MeteorDodgeGamewithShooting/item.c
- MeteorDodgeGamewithShooting/item.h
- MeteorDodgeGamewithShooting/meteor.c
- MeteorDodgeGamewithShooting/meteor.h
feat: 운석 일시정지 아이템 구현 (#71)
Closes #71 
- 아이템 관련 함수 대략적 구현(item.c, item.h)
- 운석 일시정지 아이템 구현(item.c, meteor.h, meteor.c)
- MeteorDodgeGamewithShooting/item.c
- MeteorDodgeGamewithShooting/item.h
- MeteorDodgeGamewithShooting/meteor.c
- MeteorDodgeGamewithShooting/meteor.h
https://github.com/user-attachments/assets/405aca0c-434f-434b-b346-9a9ec32652b5
- 위에서 명시한 파일 외에 .vcxproj 파일들은 솔루션 탐색기에 item관련 파일들을 추가하며 생긴 파일이므로 신경 쓰지 않으셔도 됩니다.
- item.c에서 운석 일시정지 아이템만 나타나도록 구현된 상태입니다. 추후 아이템 추가 개발 시 다른 아이템들도 나타날 수 있도록 수정하면서 개발하시면 됩니다.
- 테스트 시 아래의 코드를 main.c로 사용해주세요.
#include "bullet.h"
#include "item.h"
int main(void)
{
InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "Meteor Dodge Game With Shooting");
Player player; …
> feat: 운석 일시정지 아이템 구현 (#71)

- MeteorDodgeGamewithShooting/bullet.c
- MeteorDodgeGamewithShooting/bullet.h
- MeteorDodgeGamewithShooting/item.c
- MeteorDodgeGamewithShooting/item.h
- MeteorDodgeGamewithShooting/meteor.c
- MeteorDodgeGamewithShooting/player.c
- MeteorDodgeGamewithShooting/player.h
feat: 레이저 건 아이템 구현 (#73)
Closes #73 
- bullet.h: 레이저 속도와 길이 define, bullet 구조체에 bool 타입 isLaser 추가, FireBullet 함수의 이름을 FireBulletOrLaser로 변경, GetLaserEndPos 함수 추가 
- bullet.c: 레이저 건 아이템 구현
- player.h: player 구조체에 레이저 건 아이템 관련 요소 추가
- player.c: UpdatePlayer에서 아이템 지속 시간 확인하는 코드 추가
- meteor.c: 레이저 건 아이템과 기본 총알 모양에 따라 충돌 판정 분리, 레이저 건 아이템일 경우 총알 삭제하지 않음
- item.h: enum 수정
- item.c: 기존에 if문으로 작성되어 있던 것을 case문으로 변경하였고, 레이저 건 아이템 추가
- bullet.h
- bullet.c
- player.h
- player.c
- meteor.c
- item.h
- item.c
https://github.com/user-attachments/assets/d1d50c3d-4ee4-423b-8600-ff3a01ac6a0c
- 변경된 파일이 많습니다! 잘 확인해 주시기 바랍니다.
- item.c에서 레이저 건 아이템만 나오게 해놨기 때문에, 이 부분 필요하다면 수정하시면 됩니다.
- 레이저 건의 속도나 크기, 색깔, 지속 시간 등은 제가 임의로 설정했습니다.
- player.c와 player.h는 추가된 코드만 있습니다.
- meteor.c는 레이저 건과 기본 총알 간 모양 차이가 있어, 충돌 판정 부분을 …
> feat: 레이저 건 아이템 구현 (#73)

- MeteorDodgeGamewithShooting/item.c
- MeteorDodgeGamewithShooting/item.h
별이 온전히 그려지도록 수정 (#79)
Closes #80 
- 아이템마다 별 색상 다르도록 수정했습니다.
- DrawTriangle 버그라고 생각했던 부분 문제 발견하고 수정했습니다.....
- 꼭짓점 순서는 꼭 시계방향을 지켜주세요.
- 별거 아닌걸로 3시간은 날렸네요.
- `item.h` `item.c`
https://github.com/user-attachments/assets/7ee1b724-0991-40d5-90ad-43cb4367cc91
- 
---
> fix: 별이 온전히 그려지도록 수정 (#79)

- MeteorDodgeGamewithShooting/main.c
재시작 시 아이템 생성 시각 초기화 (#86)
Closes #86 
- 재시작 시 아이템 생성 시각 초기화했습니다.
- `main.c`
- 빌드 실행 화면, 캡처 이미지, 동작 영상 등
- main.c에 코드 한줄 추가됐습니다.
---
> fix: 재시작 시 아이템 생성 시각 초기화 (#86)
